export const CANONICAL_SHOP_ROOTS = new Set([
  "cart",
  "categories",
  "compare",
  "couponzone",
  "events",
  "largeimage",
  "login",
  "order",
  "orders",
  "payment",
  "personalpay",
  "products",
  "qas",
  "register",
  "reviews",
  "search",
  "wishlist",
]);

export const LEGACY_SHOP_ROOTS = new Set([
  "_common",
  "_head",
  "_tail",
  "ajax.action",
  "ajax.coupondownload",
  "ajax.list",
  "ajax.orderdatasave",
  "ajax.orderstock",
  "bannerhit",
  "cancel_pg.inc",
  "cartoption",
  "cartupdate",
  "category",
  "coupon",
  "event",
  "img",
  "index",
  "inicis",
  "item",
  "iteminfo",
  "itemoption",
  "itemqa",
  "itemqaform",
  "itemqaformupdate",
  "itemqalist",
  "itemrecommend",
  "itemrecommendmail",
  "itemstocksms",
  "itemstocksmsupdate",
  "itemuse",
  "itemuseform",
  "itemuseformupdate",
  "itemuselist",
  "kakaopay",
  "kcp",
  "lg",
  "list",
  "listtype",
  "mail",
  "mypage",
  "naverpay",
  "nicepay",
  "orderaddress",
  "orderaddressupdate",
  "ordercoupon",
  "ordererrormail",
  "orderform",
  "orderform.sub",
  "orderformupdate",
  "orderinquiry",
  "orderinquiry.sub",
  "orderinquirycancel",
  "orderinquiryview",
  "orderitemcoupon",
  "ordermail1.inc",
  "ordermail2.inc",
  "ordersendcost",
  "ordersendcostcoupon",
  "personalpayform",
  "personalpayform.sub",
  "personalpayformupdate",
  "personalpayresult",
  "price",
  "settle_inicis.inc",
  "settle_inicis_common",
  "settle_kakaopay.inc",
  "settle_kcp.inc",
  "settle_kcp_common",
  "settle_lg.inc",
  "settle_lg_common",
  "settle_naverpay.inc",
  "settle_nicepay.inc",
  "settle_nicepay_common",
  "settle_toss.inc",
  "settle_toss_common",
  "shop.head",
  "shop.tail",
  "taxsave",
  "toss",
  "wishupdate",
]);

export const SAFE_MEMBER_ID_RE = /^[a-zA-Z0-9_]+$/;

export function normalizeShopRouteRoot(value: string): string {
  try {
    value = decodeURIComponent(value);
  } catch {
    // Keep the original value when it is not a valid encoded segment.
  }

  return value.replace(/\.php$/i, "").toLowerCase();
}

export function isReservedShopRouteRoot(value: string): boolean {
  const segment = normalizeShopRouteRoot(value);
  return CANONICAL_SHOP_ROOTS.has(segment) || LEGACY_SHOP_ROOTS.has(segment);
}
